[project]
name = "voice-data-processing"
version = "0.1.0"
description = "processing the common voice set"
requires-python = ">=3.12"
dependencies = [
    "librosa>=0.11.0",
    "pandas>=2.3.0",
    "polars>=1.31.0",
    "tqdm>=4.67.1",
]
